kind: pipeline
type: kubernetes
name: publish-testing

steps:

- name: build
  image: golang:1.15
  commands:
  - "go env -w GO111MODULE=on"
  - "go env -w GOPROXY=https://goproxy.cn,direct"
  - "go mod download"
  - "bash ./scripts/build.sh"

- name: deploy
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
  settings:
    hosts: [ "10.23.80.124" ]
    user: release-robot
    source: ./release
    target: /data/code/point
    include: [ "point-server" ]
    delete: true
  scripts:
  - "kubectl -n testing rollout restart deployment point"

trigger:
  branch:
  - develop
  event:
  - push
