// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"point/cmd/server/config"
	"point/internal/handler/api"
)

// Injectors from wire.go:

func InitializeApplication(config2 config.Config) (application, error) {
	db, err := provideDatabase(config2)
	if err != nil {
		return application{}, err
	}
	userAssetsStore := provideAssetsStore(db)
	activityStore := provideActivityStore(db)
	activitySpecialStore := provideActivitySpecialStore(db)
	userPointDetailStore := providePointDetailStore(db)
	exchangeGoodsStore := provideExchangeGoodsStore(db)
	hd, err := provideHashids(config2)
	if err != nil {
		return application{}, err
	}
	exchangeGoodsOrderStore := provideExchangeGoodsOrderStore(db)
	server := api.New(userAssetsStore, activityStore, activitySpecialStore, userPointDetailStore, exchangeGoodsStore, hd, exchangeGoodsOrderStore)
	app := provideRouter(server)
	serverServer := provideServer(app, config2)
	mainApplication := newApplication(serverServer, userAssetsStore, hd)
	return mainApplication, nil
}
