// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"point/cmd/server/config"
	"point/internal/handler/api"
	"point/internal/service/user"
)

// Injectors from wire.go:

func InitializeApplication(config2 config.Config) (application, error) {
	db, err := provideDatabase(config2)
	if err != nil {
		return application{}, err
	}
	userAssetsStore := provideAssetsStore(db)
	userAssetsService := user.New(userAssetsStore)
	activityStore := provideActivityStore(db)
	server := api.New(userAssetsStore, userAssetsService, activityStore)
	app := provideRouter(server)
	serverServer := provideServer(app, config2)
	mainApplication := newApplication(serverServer, userAssetsStore)
	return mainApplication, nil
}
